[project]
name = "chii"
version = "1.3.1"
description = "Love Chii"

readme = "README.md"
license = "GNU GPL v3"
license-files = ["LICENSE.md"]

requires-python = ">=3.14"

dependencies = [
    "discord-py>=2.7.1",
    "peewee>=4.3.0",
    "python-dotenv>=1.2.2",
    "tzdata>=2026.3",
]

[dependency-groups]
dev = [
    "ruff>=0.16.0",
]

[tool.ruff]
line-length = 160
cache-dir = ".cache/ruff"

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "COM812", # missing-trailing-comma
    "CPY001", # missing-copyright-notice
    "D100", # undocumented-public-module
    "D101", # undocumented-public-class
    "D102", # undocumented-public-method
    "D103", # undocumented-public-function
    "D104", # undocumented-public-package
    "D105", # undocumented-magic-method
    "D106", # undocumented-public-nested-class
    "D107", # undocumented-public-init
    "D203", # incorrect-blank-line-before-class
    "D213", # multi-line-summary-second-line
    "G004", # logging-f-string
    "PLC0415", # import-outside-top-level
]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = [
    "ASYNC240", # blocking-path-method-in-async-function
    "F403", # undefined-local-with-import-star
]

"wanikani_cog.py" = [
    "S105", # hardcoded-password-string
]

[tool.basedpyright]
include = ["chii"]

typeCheckingMode = "recommended"

reportAny = false
reportImportCycles = false
reportImplicitStringConcatenation = false
reportIncompatibleVariableOverride = false
reportUnusedCallResult = false
reportUnannotatedClassAttribute = false
reportUnknownArgumentType = false
reportUnknownMemberType = false
reportUnknownVariableType = false
